Algoritmo "Exercício 44(Função 'ENQUANTO')"

Var

CT:inteiro //Contador
VCT:inteiro //Valor da contagem
NI:inteiro  //Valor inicial
NF:inteiro  //Valor final

Inicio

ESCREVAL("Insira o primeiro valor:")
LEIA(NI)

ESCREVAL("Insira o segundo valor:")
LEIA(NF)

ESCREVAL("Insira o valor da contagem:")
LEIA(VCT)

CT<-NI

ENQUANTO (CT<=NF) FACA

ESCREVAL(CT)

CT<-CT+VCT

FIMENQUANTO

Fimalgoritmo