algoritmo "Exercício 17C (Linearização)"
// Função : Aprender a linearizar operações fracionárias
// Autor : Pedro Thalysson Balbino Araújo
// Data : 20/07/2022

//"RAIZQ" Representa o síbomlo de radciação

var

H:real
X:real
K:real
R:real

inicio


ESCREVA("Digite H: ")
LEIA(H)

ESCREVA("Digite X: ")
LEIA(X)

ESCREVA("Digite K: ")
LEIA(K)

R<-"("((2*H)-((45/3*X)-(4*H*(3-H))))^(22*K)")"

ESCREVAL(R)

fimalgoritmo
