algoritmo "Exercício 12"

// Função : Pedir altura e largura de uma parede, depois calcular e exibir sua área e quantos litros de tinta bastam para pintá-la
// Autor : Pedro Thalysson Balbino Araújo
// Data : 15/07/2022
// Seção de Declarações 

var

N:real
NP:real

inicio

ESCREVA("Preço do produto: ")
LEIA (N)

NP<- N-(N*0.05)

ESCREVA("Seu preço promocional é de R$",NP)

fimalgoritmo
