Algoritmo "Exercício 47"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2022
Var

num:inteiro
sum:inteiro

Inicio
num<-500
sum<-0
enquanto (num>=0) faca
escreva(num)
sum<-sum+num
num<-num-50
fimenquanto
escreva(sum)
Fimalgoritmo