algoritmo "Exercício 14"
// Função : Pedir o total de kilômetros percorridos e dias de aluguel (carro) do usuáro. Depois, calcular e exibir o preço do aluguel
// Autor : Pedro Thalysson Balbino Araújo
// Data : 15/07/2022
// Seção de Declarações 
var

KM:real
D:real
P:real

inicio

ESCREVA("Kilômetros rodados: ")
LEIA (KM)

ESCREVA("Dias de aluguel: ")
LEIA (D)

P<-(KM*0.2)+(D*90)

ESCREVA("Preço total: R$",P)

fimalgoritmo
