Algoritmo "Exercício 46"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2022
Var

num:inteiro
sum:inteiro

Inicio
num<-6
sum<-0
enquanto (num<=100) faca
escreva(num)
sum<-sum+num
num<-num+2
fimenquanto

Fimalgoritmo