algoritmo "Exercício 11"

// Função : Pedir as variáveis A,B e C de uma equação de 2º grau, depois calcular e exibir o delta
// Autor : Pedro Thalysson Balbino Araújo
// Data : 15/07/2022
// Seção de Declarações 

var

A:real
B:real
C:real
DEL:real

inicio

ESCREVA("Insira A: ")
LEIA (A)

ESCREVA("Insira B: ")
LEIA (B)

ESCREVA("Insira C: ")
LEIA (C)

DEL<-(B)^2-(4*2*C)

ESCREVA("Seu delta é",DEL)

fimalgoritmo
