algoritmo "Testes Lógicos (Função 'SE') - Exercício 3"

// Função :
// Autor : Pedro Thalysson Balbino Araújo
// Data : 7/31/2022

var

N:caractere
A:real
B:real
M:real

inicio

ESCREVA("Insira seu nome: ")
LEIA(N)

ESCREVA("Primeira nota: ")
LEIA(A)

ESCREVA("Segunda nota: ")
LEIA(B)

M<-(A+B)/2

ESCREVAL("")

SE(M>7)ENTAO
ESCREVAL("Seu aproveitamento foi alto!")

SENAO
ESCREVAL("Seu aproveitamento foi baixo...")

FIMSE

fimalgoritmo
