algoritmo "Testes Lógicos (Função 'SE') - Exemplo 2"

// Função : Receber um número, depois declará-lo como positivo ou negativo.
// Autor : Pedro Thalysson Balbino Araújo
// Data : 25/07/2022

var

N:real

inicio

ESCREVA("Insira um número: ")
LEIA(N)

ESCREVAL("")

SE(N>=0)ENTAO
     ESCREVAL("O número",N," é positivo.")

SENAO
     ESCREVAL("O número",N," é negativo.")
FIMSE

fimalgoritmo
