algoritmo "Testes Lógicos (Função 'SE') - Exercício 2"
// Função :
// Autor : Pedro Thalysson Balbino Araújo
// Data : 26/07/2022
// Seção de Declarações 
var

D:inteiro
I:inteiro

inicio

ESCREVA("Insira seu ano de nascimento: ")
LEIA(D)

I<-2022-D

ESCREVAL("")

SE(I>=16) ENTAO
ESCREVAL("Você pode votar")

SENAO
ESCREVAL("Você ainda não pode votar")

FIMSE

fimalgoritmo
